# Spring application configuration

# Server configuration
server:
  port: 8080

# Database configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_example
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: pitaganch
    password: '@Password1'
  jpa:
    hibernate:
      ddl-auto: update

# Logging configuration
logging:
  level:
    root: INFO
    org.springframework: INFO
    com.example: DEBUG

# Other application-specific configurations
myapp:
  some-property: some-value