# Spring application configuration

# Server configuration
server:
  port: 8080

# Database configuration
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

# Logging configuration
logging:
  level:
    root: INFO
    org.springframework: INFO
    com.example: DEBUG

# Other application-specific configurations
myapp:
  some-property: some-value